# general settings
name: amp_testing
model_type: default
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
use_amp: true
#manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: DIV2K
    type: paired
    dataroot_gt: "/home/anon/nomos_uni/"
    dataroot_lq: "/home/anon/nomos_uni_downscale/"
    # (for lmdb)
    # dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub.lmdb
    # dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic_X4_sub.lmdb
    meta_info: "/home/anon/meta_info_nomos_uni_paired.txt"
    io_backend:
      type: disk
      # (for lmdb)
      # type: lmdb

    gt_size: 96
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 4
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 1

  val:
    name: Set14
    type: paired 
    dataroot_gt: "/home/anon/Downloads/validation/testset_div2k_val_small/gt/"
    dataroot_lq: "/home/anon/Downloads/validation/testset_div2k_val_small/lq/"
    io_backend:
      type: disk

# validation settings
val:
  val_freq: 1500
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 4

# network structures
network_g:
  type: compact 
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_conv: 16
  upscale: 4
  act_type: prelu

network_d:
  type: unet
  num_in_ch: 3
  num_feat: 64

# path
path:
  #pretrain_network_g: /tmp/net_g_500.pth
  #Needed only for old pretrains. All models now save to param instead of params_ema
  #param_key_g: params_ema
  resume_state: ~
  #resume_state: /home/anon/code/neosr/experiments/testing/training_states/500.state

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: AdamW
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
    fused: True
  optim_d:
    type: AdamW
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
    fused: True

  scheduler:
    type: MultiStepLR
    milestones: [60000, 190000]
    gamma: 0.5

  total_iter: 3000000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: !!float 1e-2
    reduction: mean
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      'conv5_4': 1  # before relu
    vgg_type: vgg19
    use_input_norm: true
    range_norm: false
    perceptual_weight: 1.0
    style_weight: 0
    criterion: l1
  gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 5e-3

  #net_d_iters: 1
  #net_d_init_iters: 0

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: 1000
  #use_tb_logger: false
  use_tb_logger: false
  #wandb:
  #  project: ~
  #  resume_id: ~

# dist training settings
#dist_params:
#  backend: nccl
#  port: 29500
